"""Type definitions for the market.asean_common module.

This module provides:

- ``ExchangeConfig``: Base frozen dataclass for ASEAN exchange configuration.
  Contains ``exchange_code``, ``suffix``, and ``timeout`` fields with
  ``__post_init__`` validation for the timeout range (1.0--300.0).
  Each exchange sub-package inherits from this class.
- ``TickerRecord``: Frozen dataclass representing a single ticker entry
  in the ASEAN ticker master. The ``yfinance_ticker`` field is
  automatically generated from ``ticker`` and ``yfinance_suffix``
  via ``__post_init__``.

See Also
--------
market.asean_common.constants : AseanMarket enum and YFINANCE_SUFFIX_MAP.
market.bse.types : Similar type-definition pattern for the BSE module.
"""

from dataclasses import dataclass, field

from market.asean_common.constants import AseanMarket

# =============================================================================
# ExchangeConfig base dataclass
# =============================================================================


@dataclass(frozen=True)
class ExchangeConfig:
    """Base configuration for ASEAN exchange data retrieval.

    Provides the common structure shared by all six ASEAN exchange
    config dataclasses (SGX, Bursa, SET, IDX, HOSE, PSE).
    Subclasses only need to override default values for
    ``exchange_code`` and ``suffix``.

    Parameters
    ----------
    exchange_code : str
        Exchange code identifier (e.g. ``"SGX"``, ``"BURSA"``).
    suffix : str
        yfinance ticker suffix (e.g. ``".SI"``, ``".KL"``).
    timeout : float
        HTTP request timeout in seconds (default: 30.0).
        Must be between 1.0 and 300.0 inclusive.

    Raises
    ------
    ValueError
        If timeout is outside the valid range ``[1.0, 300.0]``.

    Examples
    --------
    >>> config = ExchangeConfig(exchange_code="SGX", suffix=".SI")
    >>> config.exchange_code
    'SGX'
    >>> config.timeout
    30.0
    """

    exchange_code: str = ""
    suffix: str = ""
    timeout: float = 30.0

    def __post_init__(self) -> None:
        """Validate configuration value ranges.

        Raises
        ------
        ValueError
            If timeout is outside its valid range.
        """
        if not (1.0 <= self.timeout <= 300.0):
            raise ValueError(
                f"timeout must be between 1.0 and 300.0, got {self.timeout}"
            )


# =============================================================================
# TickerRecord dataclass
# =============================================================================


@dataclass(frozen=True)
class TickerRecord:
    """A single ticker record in the ASEAN ticker master.

    Stores metadata for an ASEAN-listed security including ticker symbol,
    company name, market, yfinance suffix, and optional financial metadata.
    The ``yfinance_ticker`` field is auto-generated by ``__post_init__``
    as ``ticker + yfinance_suffix``.

    Parameters
    ----------
    ticker : str
        Exchange-specific ticker symbol (e.g. ``"D05"`` for DBS on SGX,
        ``"1155"`` for Maybank on Bursa).
    name : str
        Company/security name (e.g. ``"DBS Group Holdings Ltd"``).
    market : AseanMarket
        The ASEAN exchange this ticker belongs to.
    yfinance_suffix : str
        The yfinance suffix for this market (e.g. ``".SI"``).
    yfinance_ticker : str
        Auto-generated yfinance ticker (``ticker + yfinance_suffix``).
        Do not set manually; it is computed in ``__post_init__``.
    sector : str | None
        GICS sector classification (e.g. ``"Financial Services"``).
    industry : str | None
        GICS industry classification (e.g. ``"Banks - Diversified"``).
    market_cap : int | None
        Market capitalisation in local currency.
    currency : str | None
        Local currency code (e.g. ``"SGD"``, ``"MYR"``).
    is_active : bool
        Whether the ticker is currently listed (default: True).

    Examples
    --------
    >>> from market.asean_common.constants import AseanMarket
    >>> record = TickerRecord(
    ...     ticker="D05",
    ...     name="DBS Group Holdings Ltd",
    ...     market=AseanMarket.SGX,
    ...     yfinance_suffix=".SI",
    ... )
    >>> record.yfinance_ticker
    'D05.SI'
    >>> record.is_active
    True
    """

    ticker: str
    name: str
    market: AseanMarket
    yfinance_suffix: str
    yfinance_ticker: str = field(init=False)
    sector: str | None = None
    industry: str | None = None
    market_cap: int | None = None
    currency: str | None = None
    is_active: bool = True

    def __post_init__(self) -> None:
        """Auto-generate yfinance_ticker from ticker and yfinance_suffix.

        Since the dataclass is frozen, ``object.__setattr__`` is used
        to set the computed field.
        """
        object.__setattr__(
            self, "yfinance_ticker", f"{self.ticker}{self.yfinance_suffix}"
        )


# =============================================================================
# Module exports
# =============================================================================

__all__ = [
    "ExchangeConfig",
    "TickerRecord",
]
